//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureFromLatexFormula.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\frac{}{}\t3\r\n\\text{}\t1\r\n\\sqrt{}\t1\r\n_{}\t1\r\n^{}\t1\r\n\\,\t0\r\n\\:\t0\r\n\\;\t0\r\n\\!\t0\r\n\\left(\\r" +
            "ight)\t7\r\n\\color{red}{}\t1")]
        public string UserFunctions {
            get {
                return ((string)(this["UserFunctions"]));
            }
            set {
                this["UserFunctions"] = value;
            }
        }
    }
}
